version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout  # checkout source code to working directory
      - run:
          name: Checkout merge commit
          command: |
            set -ex
            if [[ -n "${CIRCLE_PR_NUMBER}" ]]
            then
              FETCH_REFS="${FETCH_REFS}
              +refs/pull/${CIRCLE_PR_NUMBER}/merge:pr/${CIRCLE_PR_NUMBER}/merge"
              git fetch -u origin ${FETCH_REFS}
              git checkout "pr/${CIRCLE_PR_NUMBER}/merge"
            fi
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt -r requirements-dev.txt
      - run:
          name: Check code style
          command: |
            . venv/bin/activate
            isort --check-only
            flake8
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest
