version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout  # checkout source code to working directory
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt -r requirements-dev.txt
      - run:
          name: Check code style
          command: |
            . venv/bin/activate
            isort --check-only
            flake8
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest
